# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1

jobs:
  monorepo:
    docker: 
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Use CLI
          command: |
            chmod +x .circleci/cli
            .circleci/cli dev ci monorepo changes -p origin/master..${CIRCLE_BRANCH} -v -m directories -r .
            .circleci/cli dev ci monorepo changes -p origin/master..${CIRCLE_BRANCH} -v -m files -r .
            .circleci/cli dev ci monorepo changes -p origin/master..${CIRCLE_BRANCH} -v -m full -r .
            .circleci/cli dev ci monorepo components -p origin/master..${CIRCLE_BRANCH} -v -m all -r .
            echo "-------------"
            .circleci/cli dev ci monorepo components -p origin/master..${CIRCLE_BRANCH} -m changed -r .
      - run:
          name: Backoffice
          command: |
            cd backoffice/src
            ../../.circleci/cli dev ci monorepo run -r ../.. -p origin/master..${CIRCLE_BRANCH} -c "make test" -m current_involved
      - run:
          name: Backoffice Docker
          command: |
            cd backoffice/docker
            ../../.circleci/cli dev ci monorepo run -r ../.. -p origin/master..${CIRCLE_BRANCH} -c "make test" -m current_involved
      - run:
          name: Backoffice Helm
          command: |
            cd backoffice/helm
            ../../.circleci/cli dev ci monorepo run -r ../.. -p origin/master..${CIRCLE_BRANCH} -c "make test" -m current_involved
      - run:
          name: Console Helm
          command: |
            cd console/helm
            ../../.circleci/cli dev ci monorepo run -r ../.. -p origin/master..${CIRCLE_BRANCH} -c "make test" -m current_involved
      - run:
          name: Console
          command: |
            cd console/src
            ../../.circleci/cli dev ci monorepo run -r ../.. -p origin/master..${CIRCLE_BRANCH} -c "make test" -m current_involved
      - run:
          name: Stack
          command: |
            cd stack
            ../.circleci/cli dev ci monorepo run -r .. -p origin/master..${CIRCLE_BRANCH} -c "make test" -m current_involved
workflows:
  version: 2

  testing:
    jobs:
      - checkout_code
      - text-runner-cuke:
          requires:
            - checkout_code
      - text-runner-others:
          requires:
            - checkout_code
      - textrun-action:
          requires:
            - checkout_code
      - textrun-javascript:
          requires:
            - checkout_code
      - textrun-npm:
          requires:
            - checkout_code
      - textrun-shell:
          requires:
            - checkout_code