# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1

parameters:
  trigger:
    type: boolean
    default: true

  backoffice-src:
    type: boolean
    default: false
  backoffice-helm:
    type: boolean
    default: false
  backoffice-docker:
    type: boolean
    default: false
  console-src:
    type: boolean
    default: false
  console-helm:
    type: boolean
    default: false
  stack:
    type: boolean
    default: false

jobs:
  trigger-workflows:
    docker: 
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Trigger workflows
          command: |
            chmod +x .circleci/circle_trigger.sh 
            .circleci/circle_trigger.sh

  hello: 
    parameters:
      msg:
        type: string
        default: World
    docker: 
      - image: cimg/base:stable
    steps:
      - checkout 
      - run: 
          name: "Hello << parameters.msg >>!"
          command: |
            echo "Hello << parameters.msg >>!"
            shellPath=$(<< parameters.msg >>//"_"/"\/")
            ./${shellPath}/<< parameters.msg >>.sh

workflows:
  monorepo:
    when: << pipeline.parameters.trigger >>
    jobs:
      - trigger-workflows

  backoffice-src:
    when: << pipeline.parameters.backoffice >>
    jobs:
      - hello:
          msg: backoffice-src

  backoffice-docker:
    when: << pipeline.parameters.backoffice >>
    jobs:
      - hello:
          msg: backoffice-docker

  backoffice-helm:
    when: << pipeline.parameters.backoffice >>
    jobs:
      - hello:
          msg: backoffice-helm

  console-src:
    when: << pipeline.parameters.console >>
    jobs:
      - hello:
          msg: console-src

  console-helm:
    when: << pipeline.parameters.console >>
    jobs:
      - hello:
          msg: console-helm
