# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1

jobs:
  monorepo:
    docker: 
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Use CLI
          command: |
            chmod +x .circleci/cli
            .circleci/cli dev ci monorepo changes -p origin/master..${CIRCLE_BRANCH} -v -m directories -r .
            .circleci/cli dev ci monorepo changes -p origin/master..${CIRCLE_BRANCH} -v -m files -r .
            .circleci/cli dev ci monorepo changes -p origin/master..${CIRCLE_BRANCH} -v -m full -r .
            .circleci/cli dev ci monorepo components -p origin/master..${CIRCLE_BRANCH} -v -m all -r .
            echo "-------------"
            .circleci/cli dev ci monorepo components -p origin/master..${CIRCLE_BRANCH} -v -m changed -r .
workflows:
  monorepo:
    jobs:
      - monorepo

